/// Marks a class as a REST API definition.
///
/// The annotated class must be abstract and will have a concrete implementation
/// generated by the Netrofit code generator.
///
/// Example:
/// ```dart
/// @RestApi(baseUrl: "https://api.example.com")
/// abstract class UserApi {
///   factory UserApi({required HttpAdapter httpAdapter}) = _$UserApiImpl;
///
///   @Get("/users")
///   Future<ApiResult<List<User>>> getUsers();
/// }
/// ```
class RestApi {
  /// The base URL for all endpoints in this API.
  final String baseUrl;

  /// Default connection timeout for all requests.
  final Duration? connectTimeout;

  /// Default receive timeout for all requests.
  final Duration? receiveTimeout;

  /// Default send timeout for all requests.
  final Duration? sendTimeout;

  const RestApi({
    required this.baseUrl,
    this.connectTimeout,
    this.receiveTimeout,
    this.sendTimeout,
  });
}
