name: netrofit
repository: https://github.com/user/netrofit

packages:
  - packages/**
  - example

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    run: dart analyze --fatal-infos
    exec:
      concurrency: 1
    packageFilters:
      flutter: false
      
  test:
    run: dart test
    exec:
      concurrency: 1
    packageFilters:
      dirExists: test

  publish:dry-run:
    run: dart pub publish --dry-run
    exec:
      concurrency: 1
    packageFilters:
      private: false
